name: Branch Tests

on:
  push:
    branches-ignore: [ main ]
    paths:
      - 'typescript/**'
      - '.github/workflows/branch-tests.yml'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run unit tests
        uses: ./.github/actions/run-unit-tests
        with:
          node-version: '20'
