name: Branch Tests

on:
  push:
    branches-ignore: [ main ]
    paths:
      - 'typescript/**'
      - '.github/workflows/branch-tests.yml'

permissions:
  contents: read

jobs:
  unit-tests:
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      node-version: ${{ env.NODE_VERSION }}
