name: Branch Tests

on:
  push:
    branches-ignore: [ main ]
    paths:
      - 'typescript/**'
      - '.github/workflows/branch-tests.yml'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup and install
        uses: ./.github/actions/setup-and-install
        with:
          node-version: '20'

      - name: Run unit tests
        working-directory: typescript
        run: npm run test:unit
