name: PR Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'typescript/**'
      - '.github/workflows/pr-tests.yml'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        uses: ./.github/actions/run-unit-tests
        with:
          node-version: '20'

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup and install
        uses: ./.github/actions/setup-and-install
        with:
          node-version: '20'

      - name: Run integration tests
        working-directory: typescript
        run: npm run test:integration

      - name: Run tool-calling validation tests (single LLM)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        working-directory: typescript
        run: npm run test
