name: Run E2E Tests (typescript)

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version
        required: false
        default: '20'
        type: string
      workdir:
        description: Working directory
        required: false
        default: 'typescript'
        type: string
    secrets:
      OPENAI_API_KEY:
        required: true
      ACCOUNT_ID:
        required: true
      PRIVATE_KEY:
        required: true

permissions:
  contents: read

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    env:
      WORKDIR: typescript
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      E2E_LLM_PROVIDER: ${{ vars.E2E_LLM_PROVIDER }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          cache-dependency-path: 'typescript/package-lock.json'

      - name: Install dependencies
        working-directory: ${{ inputs.workdir }}
        run: npm ci

      - name: Run E2E tests (throttled)
        working-directory: ${{ inputs.workdir }}
        env:
          SLOW_TEST_DELAY_MS: '30000'
        run: npm run test e2e -- --sequence.concurrent=false
