name: Run Integration Tests (typescript)

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version
        required: false
        default: '20'
        type: string
      workdir:
        description: Working directory
        required: false
        default: 'typescript'
        type: string
    secrets:
      OPENAI_API_KEY:
        required: true
      ACCOUNT_ID:
        required: true
      PRIVATE_KEY:
        required: true
    outputs: {}

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      WORKDIR: typescript
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      E2E_LLM_PROVIDER: ${{ vars.E2E_LLM_PROVIDER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          cache-dependency-path: 'typescript/package-lock.json'
      - name: Install dependencies
        working-directory: ${{ inputs.workdir }}
        run: npm ci
      - name: Run integration tests
        working-directory: ${{ inputs.workdir }}
        run: npm run test integration
